### ISSUE TITLE
With `delay > 0`, Keep the line visible if the cursor stays in the same line

### ISSUE THREAD

**Issue by afgomez** [braxtons12/blame_line.nvim#5]
👋 thanks for your plugin!

I noticed that when a delay is specified in the config and the cursor moves in the same line, the blame info disappears and appears again.

Ideally, if the cursor stays in the same line the blame line shouldn't redraw.

Uploading blame-redraw.mov…

**Comment by braxtons12** [comment]
Hi!
This is a good point, I'll implement this check as soon as I get the time.
